### ISSUE TITLE
run specjvm2008 on openjdk11

### ISSUE THREAD

**Issue by piaoxuebingfeng** [connorimes/SPECjvm2008#1]
how can i run specjvm2008 on openjdk11?
now,i get some errors:

Error in setup of Benchmark.
spec.harness.StopBenchmarkException: Error invoking bmSetupBenchmarkMethod
	at spec.harness.ProgramRunner.invokeBmSetupBenchmark(ProgramRunner.java:185)
	at spec.harness.ProgramRunner.runBenchmark(ProgramRunner.java:301)
	at spec.harness.ProgramRunner.run(ProgramRunner.java:98)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at spec.harness.ProgramRunner.invokeBmSetupBenchmark(ProgramRunner.java:183)
	... 2 more
Caused by: java.lang.NoClassDefFoundError: com/sun/tools/javac/util/JavacFileManager
	at spec.benchmarks.compiler.MainBase.preSetupBenchmark(MainBase.java:38)
	at spec.benchmarks.compiler.sunflow.Main.setupBenchmark(Main.java:33)
	... 7 more

Warmup (120s) begins: Wed Apr 21 20:04:07 CST 2021
Warmup (120s) ends:   Wed Apr 21 20:04:07 CST 2021
Warmup (120s) result:  **NOT VALID**
Error in tear down of Benchmark.
spec.harness.StopBenchmarkException: Error invoking bmTearDownBenchmarkMethod
	at spec.harness.ProgramRunner.invokeBmTearDownBenchmark(ProgramRunner.java:209)
	at spec.harness.ProgramRunner.runBenchmark(ProgramRunner.java:390)
	at spec.harness.ProgramRunner.run(ProgramRunner.java:98)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at spec.harness.ProgramRunner.invokeBmTearDownBenchmark(ProgramRunner.java:207)
	... 2 more
Caused by: java.lang.NullPointerException
	at spec.benchmarks.compiler.MainBase.tearDownBenchmark(MainBase.java:48)
	... 7 more

Errors in benchmark: compiler.sunflow
   Error in setup of Benchmark.
   Error in tear down of Benchmark.
  [warmup] Error in setup of iteration.
  [warmup] spec.harness.StopBenchmarkException: Error creating benchmark instance for spec.benchmarks.compiler.sunflow.Main
spec.harness.ProgramRunner.createBmInstance(ProgramRunner.java:169)
spec.harness.ProgramRunner.runIteration(ProgramRunner.java:455)
spec.harness.ProgramRunner.runBenchmark(ProgramRunner.java:316)
spec.harness.ProgramRunner.run(ProgramRunner.java:98)

**Comment by connorimes** [comment]
There appear to be dependencies on classes that are internal to the JDK, which OpenJDK11 may not implement.  You may have to use the Oracle JDK.

**Comment by Shilei-Wang-code** [comment]
I have the same problem. Have you solved your problem
